WebBookStore/Controllers/BookStoreController.cs
using System;
using System.Web;
using WebBookStore.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using PagedList;
using PagedList.Mvc;
namespace BookStore.Controllers
{
    public class BookStoreController : Controller
    {
        dbQLBookstoreDataContext data = new dbQLBookstoreDataContext();
        private List<Sach> Laysachmoi(int count)
        {
            return data.Saches.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        public ActionResult Index(int? page)
        {
            int pageSize = 3;
            int pageNum = (page ?? 1);
            var sachmoi = Laysachmoi(15);
            return View(sachmoi.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Topic()
        {
            var chude = from cd in data.ChuDes select cd;
            return PartialView(chude);
        }
        public ActionResult Publisher()
        {
            var nhaxuatban = from nxb in data.NhaXuatBans select nxb;
            return PartialView(nhaxuatban);
        }
        public ActionResult BookByTopic(int id)
        {
            var sach = from s in data.Saches where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult BookByPublisher(int id)
        {
            var sach = from s in data.Saches where s.MaNXB == id select s;
            return View(sach);
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.Saches where s.MaSach == id select s;
            return View(sach.Single());
        }

    }
}

WebBookStore/Views/BookStore/BookByPublisher.cshtml
@model IEnumerable<WebBookStore.Models.Sach>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center; color:red"> BOOK BY PUBLICATION </h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                    <a href="@Url.Action("Details", "BookStore", new {id = sach.MaSach})">
                        <img alt="@sach.TenSach" src="~/product_imgs/@sach.AnhBia" />
                        <span>@sach.TenSach</span>
                    </a>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
            </div>
        </div>
    }
</div>

WebBookStore/Views/BookStore/BookByTopic.cshtml
@model IEnumerable<WebBookStore.Models.Sach>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center; color:red"> BOOK BY TOPIC </h3>

<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">               
                    <a href="@Url.Action("Details", "BookStore", new {id = sach.MaSach})">
                        <img alt="@sach.TenSach" src="~/product_imgs/@sach.AnhBia" />
                        <span>@sach.TenSach</span>
                    </a>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
            </div>
        </div>
    }
</div>

WebBookStore/Views/BookStore/Chude.cshtml
@model IEnumerable<WebBookStore.Models.ChuDe>
<p class="lead">TOPIC</p>
<div class="list-group">
    @foreach (var item in Model)
    {
    <a href="@Url.Action("SPTheochude", "BookStore", new { id = item.MaCD})" class="list-group-item">      
        @item.TenChuDe
    </a>
    }
</div>

WebBookStore/Views/BookStore/Details.cshtml
<style>
    .dathang {
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        -webkit-transition-duration: 0.4s; /* Safari */
        transition-duration: 0.4s;
        font-weight: bold;
        float: right;
    }

     .dathang:hover {
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
        }
</style>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2 style="text-align:center">BOOK DETAILS </h2>
<h3 style="font-weight: bold;">Title: @Model.TenSach</h3>

<div class="col-sm-6 col-lg-6 col-md-6">
    <div>
        <img alt="@Model.TenSach" width="100%" src="~/product_imgs/@Model.AnhBia" />
    </div>
</div>

<div class="col-sm-6 col-lg-6 col-md-6">
    <div>
        <p style="color:#ff0000; font-size:25px"> DESCRIPTION: </p>
        <p style="text-align:justify"> @Model.MoTa  </p>
    </div>
    <div>
        <p style="color:#ff0000; font-size:25px"> PRICE: @Model.GiaBan USD   </p>

    </div>
    <div class="dathang">
        <a style="color: crimson " 
           href="@Url.Action("ThemGioHang", "GioHang", 
                new {@iMaSach= @Model.MaSach, @strURL=Request.Url.ToString() })">ORDER NOW</a>
    </div>
</div>

WebBookStore/Views/BookStore/Index.cshtml
@using WebBookStore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<Sach>
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center; color:red">NEW BOOK</h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details", "BookStore", new {id = sach.MaSach})">
                    <img alt="@sach.TenSach" src="~/product_imgs/@sach.AnhBia" />
                    <span>@sach.TenSach</span>
                </a>
                <div class="ratings">
                    <p class="pull-right">15 reviews</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                    </p>
                </div>
            </div>
        </div>
    }
</div>
Page @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
<div class="Menupage">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

<style>
    .Menupage li {
        display: inline;
    }
</style>

WebBookStore/Views/BookStore/Nhaxuatban.cshtml
@model IEnumerable<WebBookStore.Models.NhaXuatBan>
<p class="lead">PUBLISHING COMPANY</p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SPTheoNXB", "BookStore", new { id = item.MaNXB})" class="list-group-item">
            @item.TenNXB
        </a>
    }
</div>

WebBookStore/Views/BookStore/Publisher.cshtml
@model IEnumerable<WebBookStore.Models.NhaXuatBan>
<p class="lead">BOOK BY PUBLISHER</p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("BookByPublisher", "BookStore", new { id = item.MaNXB})" class="list-group-item">
            @item.TenNXB
        </a>
    }
</div>

WebBookStore/Views/BookStore/Publishingcompany.cshtml
@model IEnumerable<WebBookStore.Models.NhaXuatBan>
<p class="lead">PUBLISHING COMPANY</p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("Publishing", "BookStore", new { id = item.MaNXB})" class="list-group-item">
            @item.TenNXB
        </a>
    }
</div>

WebBookStore/Views/BookStore/SPTheoNXB.cshtml
@model IEnumerable<WebBookStore.Models.Sach>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center; color:red"> BOOK BY PUBLICATION </h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                    <a href="@Url.Action("Details", "BookStore", new {id = sach.MaSach})">
                        <img alt="@sach.TenSach" src="~/product_imgs/@sach.AnhBia" />
                        <span>@sach.TenSach</span>
                    </a>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
            </div>
        </div>
    }
</div>

WebBookStore/Views/BookStore/SPTheochude.cshtml
@model IEnumerable<WebBookStore.Models.Sach>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center; color:red"> BOOK BY TOPIC </h3>

<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">               
                    <a href="@Url.Action("Details", "BookStore", new {id = sach.MaSach})">
                        <img alt="@sach.TenSach" src="~/product_imgs/@sach.AnhBia" />
                        <span>@sach.TenSach</span>
                    </a>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
            </div>
        </div>
    }
</div>

WebBookStore/Views/BookStore/Topic.cshtml
@model IEnumerable<WebBookStore.Models.ChuDe>
<p class="lead">TOPIC</p>
<div class="list-group">
    @foreach (var item in Model)
    {
    <a href="@Url.Action("BookByTopic", "BookStore", new { id = item.MaCD})" class="list-group-item">      
        @item.TenChuDe
    </a>
    }
</div>